import PDFDocument from "pdfkit";

export async function generateReport(
  markdownContent: string,
  fileName: string
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margins: { top: 60, bottom: 60, left: 50, right: 50 },
      info: {
        Title: "Erasmus+ Application Evaluation Report",
        Author: "EasyApplications",
      },
    });

    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const pageWidth = doc.page.width;

    // Header gradient bar
    doc.rect(0, 0, pageWidth, 8).fill("#3C3CE6");

    // Title
    doc.fontSize(22).fillColor("#3C3CE6").text("EasyApplications", 50, 30);
    doc
      .fontSize(10)
      .fillColor("#666666")
      .text("AI-Powered Erasmus+ Application Review", 50, 55);

    doc.moveDown(2);
    doc.fontSize(16).fillColor("#1A1A6E").text("Evaluation Report");
    doc.fontSize(10).fillColor("#999999").text(`Document: ${fileName}`);
    doc.text(`Generated: ${new Date().toLocaleDateString("en-GB")}`);

    doc.moveDown(1);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke("#CCCCCC");
    doc.moveDown(1);

    // Render markdown-like content
    const lines = markdownContent.split("\n");
    for (const line of lines) {
      // Check if we need a new page
      if (doc.y > doc.page.height - 100) {
        doc.addPage();
      }

      if (line.startsWith("### ")) {
        doc.moveDown(0.3);
        doc
          .fontSize(12)
          .fillColor("#4F5CE8")
          .text(line.replace("### ", ""), { underline: false });
        doc.moveDown(0.2);
      } else if (line.startsWith("## ")) {
        doc.moveDown(0.5);
        doc
          .fontSize(14)
          .fillColor("#3C3CE6")
          .text(line.replace("## ", ""));
        doc.moveDown(0.3);
      } else if (line.startsWith("# ")) {
        doc.moveDown(0.5);
        doc
          .fontSize(16)
          .fillColor("#1A1A6E")
          .text(line.replace("# ", ""));
        doc.moveDown(0.3);
      } else if (line.startsWith("- ") || line.startsWith("* ")) {
        doc
          .fontSize(10)
          .fillColor("#333333")
          .text(`  \u2022  ${line.replace(/^[-*] /, "")}`, { indent: 10 });
      } else if (line.match(/^\d+\./)) {
        doc.fontSize(10).fillColor("#333333").text(line, { indent: 10 });
      } else if (line.startsWith("**") && line.endsWith("**")) {
        doc
          .fontSize(10)
          .fillColor("#1A1A6E")
          .text(line.replace(/\*\*/g, ""));
      } else if (line.includes("Score:") || line.includes("/100")) {
        doc.fontSize(11).fillColor("#3C3CE6").text(line.replace(/\*\*/g, ""));
      } else if (line.trim()) {
        // Strip inline markdown bold/italic for plain text rendering
        const cleanLine = line.replace(/\*\*(.*?)\*\*/g, "$1").replace(/\*(.*?)\*/g, "$1");
        doc.fontSize(10).fillColor("#333333").text(cleanLine);
      } else {
        doc.moveDown(0.3);
      }
    }

    // Footer
    doc.moveDown(2);
    if (doc.y > doc.page.height - 80) {
      doc.addPage();
    }
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke("#CCCCCC");
    doc.moveDown(0.5);
    doc
      .fontSize(8)
      .fillColor("#999999")
      .text(
        "This report was generated by EasyApplications using AI analysis. " +
          "It is intended as guidance and does not guarantee application success.",
        { align: "center" }
      );

    doc.end();
  });
}
