import Header from "@/components/Header";
import Footer from "@/components/Footer";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service - EasyApplications",
};

export default function TermsOfService() {
  return (
    <>
      <Header />
      <main className="min-h-screen bg-white py-20 px-6">
        <article className="max-w-3xl mx-auto prose prose-gray">
          <h1 className="text-3xl font-bold text-brand-900 mb-2">
            Terms of Service
          </h1>
          <p className="text-gray-500 mb-10">Last updated: March 8, 2026</p>

          <section className="space-y-6 text-gray-700 leading-relaxed">
            <div>
              <h2 className="text-xl font-semibold text-brand-900 mt-8 mb-3">
                1. Service Description
              </h2>
              <p>
                EasyApplications provides an AI-powered evaluation service for
                Erasmus+ project applications. You upload your application
                document, pay a one-time fee, and receive a detailed evaluation
                report via email with scores, feedback, and improvement
                suggestions.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-brand-900 mt-8 mb-3">
                2. Acceptance of Terms
              </h2>
              <p>
                By using EasyApplications and completing a purchase, you agree
                to these Terms of Service and our{" "}
                <a href="/privacy" className="text-brand-600 underline">
                  Privacy Policy
                </a>
                .
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-brand-900 mt-8 mb-3">
                3. Payment &amp; Pricing
              </h2>
              <p>
                The evaluation service costs a one-time fee as displayed on the
                website at the time of purchase. Payments are processed securely
                through Stripe. All prices are in euros (EUR) and are inclusive
                of any applicable taxes. VAT is exempt under the Dutch Small
                Business Scheme (KOR), Article 25 Dutch VAT Act 1968, and the
                EU Small Business Scheme (EU-KOR), EU Directive 2020/285.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-brand-900 mt-8 mb-3">
                4. Delivery
              </h2>
              <p>
                After successful payment, your evaluation report will be
                generated and sent to the email address you provided. Delivery
                typically takes a few minutes but may take longer depending on
                document complexity and system load.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-brand-900 mt-8 mb-3">
                5. AI-Generated Content Disclaimer
              </h2>
              <p>
                The evaluation report is generated by artificial intelligence
                (Anthropic&apos;s Claude). While our AI is trained to evaluate
                applications based on official Erasmus+ criteria, the scores and
                feedback are <strong>indicative only</strong> and may differ from
                actual evaluator assessments. EasyApplications does not
                guarantee any specific outcome for your Erasmus+ application.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-brand-900 mt-8 mb-3">
                6. Refund Policy
              </h2>
              <p>
                Since the evaluation report is a digital product delivered
                immediately after purchase, refunds are generally not available
                once the report has been generated and delivered. If you
                experience technical issues that prevent delivery of your
                report, please contact us at{" "}
                <a
                  href="mailto:contact@easyapplications.ai"
                  className="text-brand-600 underline"
                >
                  contact@easyapplications.ai
                </a>{" "}
                and we will resolve the issue or provide a refund.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-brand-900 mt-8 mb-3">
                7. Accepted Documents
              </h2>
              <p>
                We accept Erasmus+ application documents in PDF, DOC, and DOCX
                format, up to 10 MB in size. Documents that are too short,
                empty, or not related to Erasmus+ applications may not produce
                meaningful results.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-brand-900 mt-8 mb-3">
                8. Intellectual Property
              </h2>
              <p>
                You retain all rights to your uploaded documents. By using our
                service, you grant us a license to process your document for the
                purpose of generating your evaluation report, and to store and
                use the document for improving our services, including the
                development of AI-based tools.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-brand-900 mt-8 mb-3">
                9. Limitation of Liability
              </h2>
              <p>
                EasyApplications is provided &quot;as is&quot;. We are not liable for
                any indirect, incidental, or consequential damages arising from
                your use of the service. Our total liability is limited to the
                amount you paid for the evaluation.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-brand-900 mt-8 mb-3">
                10. Changes to These Terms
              </h2>
              <p>
                We may update these terms from time to time. Continued use of
                the service after changes constitutes acceptance of the updated
                terms.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-brand-900 mt-8 mb-3">
                11. Governing Law
              </h2>
              <p>
                These terms are governed by the laws of the Netherlands. Any
                disputes will be subject to the jurisdiction of the Dutch
                courts.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold text-brand-900 mt-8 mb-3">
                12. Contact
              </h2>
              <p>
                For any questions about these terms, contact us at{" "}
                <a
                  href="mailto:contact@easyapplications.ai"
                  className="text-brand-600 underline"
                >
                  contact@easyapplications.ai
                </a>
                .
              </p>
            </div>
          </section>
        </article>
      </main>
      <Footer />
    </>
  );
}
